AWSTemplateFormatVersion: '2010-09-09'
Description: ALB
Parameters:
  Prefix:
    Description: Enter a prefix of this system.
    Type: String
    Default: devio-alb-iptg
  TargetIP:
    Type: String
    Description: IP address of the target

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Type: application
      Scheme: internal
      IpAddressType: ipv4
      Subnets: 
        - Fn::ImportValue: !Sub ${Prefix}-subnet2-a
        - Fn::ImportValue: !Sub ${Prefix}-subnet2-c
      SecurityGroups:
        - Fn::ImportValue: !Sub ${Prefix}-sg-alb
      Name: !Sub ${Prefix}-alb
      # LoadBalancerAttributes:
      #   - Key:
      #     Value: 
      # SubnetMappings: --> not requied in Internal ALB
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-alb
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Sub ${Prefix}-alb-tg
      TargetType: ip
      Protocol: HTTP
      Port: 80
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-vpc2
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-alb-tg
      Targets:
        - AvailabilityZone: all
          Id: !Ref TargetIP
          Port: 80
      # 
      # HealthCheckEnabled: Boolean
      # HealthCheckIntervalSeconds: Integer
      # HealthCheckPath: String
      # HealthCheckPort: String
      # HealthCheckProtocol: String
      # HealthCheckTimeoutSeconds: Integer
      # HealthyThresholdCount: Integer
      # Matcher: Matcher
      # TargetGroupAttributes: 
      #   - Key: proxy_protocol_v2.enabled
      #     Value: false
      #   - Key: deregistration_delay.timeout_seconds
      #     Value: 300
      # UnhealthyThresholdCount: Integer
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      # SslPolicy: String
      # Certificates: - Certificate

Outputs:
  ALBDNSName:
    Value: !GetAtt ALB.DNSName
    Export:
      Name: !Sub ${Prefix}-alb-dns-name
  ALB:
    Value: !Ref ALB
    Export:
      Name: !Sub ${Prefix}-alb
  ALBTargetGroup:
    Value: !Ref ALBTargetGroup
    Export:
      Name: !Sub ${Prefix}-alb-tg
