AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance (app)
Parameters:
  Prefix:
    Description: Enter a prefix of this system.
    Type: String
    Default: devio-ha-proxy
  Ec2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-Japanese-Full-Base
  Ec2InstanceType:
    Type: String
    Default: t3.micro
  Ec2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable access to instances.
 
Resources:
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Ec2ImageId
      InstanceType: !Ref Ec2InstanceType
      KeyName: !Ref Ec2KeyName  
      SubnetId:
        Fn::ImportValue: !Sub ${Prefix}-subnet1
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Prefix}-app-sg
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - !Sub |
                <powershell>
                reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings" /f /v ProxyEnable /t reg_dword /d 1
              - reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings" /f /v ProxyServer /t reg_sz /d
              - " "
              - Fn::ImportValue: !Sub ${Prefix}-nlb-dns-name
              - ":3128\n"
              - "</powershell>"
          
      Tags:
        - Key: Name
          Value: !Sub ${Prefix}-ec2-app

Outputs:
  AppInstance:
    Value: !Ref AppInstance
    Export:
      Name: !Sub ${Prefix}-ec2-app
  PublicIp:
    Description: AppServer Public IP
    Value: !GetAtt AppInstance.PublicIp
